services:
  dev-postgres:
    image: postgres:15.1-alpine
    ports:
      - 5439:5432
    environment:
      POSTGRES_USER: social
      POSTGRES_PASSWORD: social
      POSTGRES_DB: social
    restart: always
    networks:
      - lesson
networks:
  lesson: